### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by whinee** [4a454646/github-purple#1]
Hello, I want to fork your project and modify it, adding stuff from https://github.com/doki-theme/doki-theme-vscode and my own bits. I notice however that this repository lacks license. What license should this be under? I just want to assure that the authors of the projects I've copied from is credited properly. Thanks!

**Comment by jeff-j-chen** [comment]
Thank you for the reminder! I have added a MIT license, since that is the license the original github-vscode-theme repository was created with.
